In [1]:
import pandas as pd

In [ ]:
def total_goles_equipo(df, nombre_equipo):
    """
    Calcula el total de goles de un equipo
    """
    nombre_equipo_lower = nombre_equipo.lower()
    df_equipo = df[df['Team'].str.lower() == nombre_equipo_lower]
    if df_equipo.empty:
        return f"No hay resultados para el equipo '{nombre_equipo}'."
    total_goles = df_equipo['Goals'].sum()
    return f"El total de goles del equipo {nombre_equipo} es: {total_goles}"

In [22]:
def goleadores(opcion):
    """
    Devuelve los goleadores de la liga.
    """
    if opcion == 'top_10':
        gol_10= df['Goals'].iloc[10]
        return df[df['Goals'] >= gol_10]
    elif opcion == 'top_5':
        gol_5= df['Goals'].iloc[5]
        return df[df['Goals'] >= gol_5]
    elif opcion == 'top_3':
        gol_3= df['Goals'].iloc[3]
        return df[df['Goals'] >= gol_3]
    elif opcion == 'top_1':
        gol_1= df['Goals'].iloc[1]
        return df[df['Goals'] >= gol_1]
    else:
        return "Opción no válida. Por favor, elige entre 'top_10', 'top_5', 'top_3' o 'top_1'."

In [26]:
def jugadores_info(nombre):
    """
    Devuelve la información de los jugadores.
    """
    df['Player'] = df['Player'].str.lower()  # Normalizar nombres de jugadores a minúsculas
    nombre = nombre.lower()  # Normalizar el nombre del jugador a minúsculas
    df_player = df[df['Player'] == nombre]
    return df_player.to_dict(orient='records')

In [5]:
df = pd.read_csv(r'..\datos\Copa_Libertadores_2023_Complete_Goal_Scorers.csv')

In [23]:
df

,Player,Team,Country,Team Nationality,Goals,Penalty Goals,Team Total Goals
0,Germán Cano,Fluminense RJ,Argentina,Brasil,13,0,24
1,Paulinho,Atlético Mineiro,Brasil,Brasil,7,0,14
2,Dorlan Pabón,Atlético Nacional,Colombia,Colombia,6,2,12
3,Alan Patrick,Internacional,Brasil,Brasil,5,1,19
4,Artur,Palmeiras,Brasil,Brasil,5,0,22
...,...,...,...,...,...,...,...
227,Yoshimar Yotún,Sporting Cristal,Perú,Perú,1,0,14
228,Diego Zabala,Nacional,Uruguay,Uruguay,1,0,11
229,Facundo Zabala,Club Olimpia,Argentina,Paraguay,1,0,17
230,Cristián Zapata,Atlético Nacional,Colombia,Colombia,1,0,12
231,Yorman Zapata,CD Magallanes,Colombia,Chile,1,0,7

In [20]:
# Supongamos que ya tienes cargado el DataFrame df
# Ejemplo de uso de la función:

nombre_equipo = input("Ingrese el nombre del equipo: ")
resultado = total_goles_equipo(df, nombre_equipo)
print(resultado)

El total de goles del equipo PALMEIRAS es: 22

In [24]:
goleadores('top_10')  # Ejemplo de uso

,Player,Team,Country,Team Nationality,Goals,Penalty Goals,Team Total Goals
0,Germán Cano,Fluminense RJ,Argentina,Brasil,13,0,24
1,Paulinho,Atlético Mineiro,Brasil,Brasil,7,0,14
2,Dorlan Pabón,Atlético Nacional,Colombia,Colombia,6,2,12
3,Alan Patrick,Internacional,Brasil,Brasil,5,1,19
4,Artur,Palmeiras,Brasil,Brasil,5,0,22
5,Luciano Pons,Independiente Medellín,Argentina,Colombia,5,0,16
6,Luis Advíncula,Boca Juniors,Perú,Argentina,4,0,13
7,Rubén Bentancourt,Liverpool,Uruguay,Uruguay,4,1,4
8,Ronnie Fernández,Bolívar,Chile,Bolivia,4,0,13
9,John Kennedy,Fluminense RJ,Brasil,Brasil,4,0,24
10,Guillermo Paiva,Club Olimpia,Paraguay,Paraguay,4,0,17
11,Enrique Triverio,The Strongest,Argentina,Bolivia,4,1,5
12,Enner Valencia,Internacional,Ecuador,Brasil,4,0,19
13,Vítor Roque,Athletico Paranaense,Brasil,Brasil,4,0,12

In [ ]:
##### INICIO DE LA CREACION DE API #####

rom fastapi import FastAPI
from pydantic import BaseModel
import pandas as pd

# Crear la instancia de FastAPI
app = FastAPI()

# Cargar los datos
df = pd.read_csv('..\datos\Copa_Libertadores_2023_Complete_Goal_Scorers.csv')

# Modelo de Pydantic para la validación de datos
class Player(BaseModel):
    name: str
    team: str
    country: str
    team_nationality: str
    goals: int
    penalty_goals: int